name: Build Orora CLI
on:
  schedule:
    - cron: "0 8,20 * * *" # 7am and 7pm every day

  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1
  BUILDX_EXPERIMENTAL: 1
  IMAGE_NAME: orora-cli
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    container:
      image: fedora:39
      options: --privileged
    outputs:
      tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf -y install buildah docker podman

      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      - name: Image Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          flavor: |
            latest=true
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=schedule,pattern=nightly
          images: |
            ${{ steps.registry_case.outputs.lowercase }}/${{ env.IMAGE_NAME }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          oci: false
          layers: true
          labels: |
            ${{ steps.meta.outputs.labels }}
          tags: |
            ${{steps.meta.outputs.tags}}
          containerfiles: |
            ./Containerfile

      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          tags: ${{ steps.build_image.outputs.tags }}
          image: ${{ steps.build_image.outputs.image }}
          registry: ${{ steps.registry_case.outputs.lowercase }}
          extra-args: |
            --disable-content-trust

  sign:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    permissions:
      id-token: write
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: sigstore/cosign-installer@v3

      - name: Sign the images
        run: cosign sign -y ${TAGS}
        env:
          TAGS: ${{needs.build.outputs.tags}}

      - name: Verify the pushed tags
        run: |
          cosign verify \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            --certificate-identity-regexp "${{ github.server_url }}/${{ github.repository }}" \
            ${TAGS}
        env:
          TAGS: ${{needs.build.outputs.tags}}
